language: php
php:
    - 5.6
    - 5.5
    - hhvm
    - 7

services:
    - redis-server

before_script:
    - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]] ; then echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - composer selfupdate
    - composer install --prefer-source

script: ./vendor/bin/phpunit
