parameters:
    mcfedr_resque.host: ~
    mcfedr_resque.port: ~
    mcfedr_resque.default_queue: ~

services:
    mcfedr_resque.manager:
        class: Mcfedr\ResqueBundle\Manager\ResqueManager
        arguments:
            - "%mcfedr_resque.host%"
            - "%mcfedr_resque.port%"
            -
                'kernel.root_dir': '%kernel.root_dir%'
                'kernel.environment': '%kernel.environment%'
                'kernel.debug': '%kernel.debug%'
            - "%mcfedr_resque.default_queue%"
